name: TUF-on-CI online signing

permissions: {}

on:
  schedule:
    - cron: "17 1,7,13,19 * * *"
  push:
    branches: [main]
    # paths: ["metadata/**"]
  workflow_dispatch:

jobs:
  online-sign:
    runs-on: ubuntu-latest

    permissions:
      id-token: "write" # for OIDC identity access
      contents: "write" # for commiting snapshot/timestamp changes
      actions: "write" # for dispatching publish workflow

    steps:
      - id: online-sign
        uses: jonnystoten/tuf-on-ci/actions/online-sign@485b18a48978bca91d321a2562f3cfa2b5daf32e
        with:
          gcp_workload_identity_provider: ${{ vars.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          gcp_service_account: ${{ vars.GCP_SERVICE_ACCOUNT }}
          aws_role_to_assume: ${{ vars.AWS_ROLE_TO_ASSUME }}
          aws_region: ${{ vars.AWS_REGION }}
